# Generated by Django 4.2.30 on 2026-09-20 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendees', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exhibitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('tier', models.CharField(choices=[('platinum', 'Platinum sponsor'), ('gold', 'Gold sponsor'), ('silver', 'Silver sponsor'), ('exhibitor', 'Exhibitor')], default='exhibitor', max_length=20)),
                ('blurb', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('logo_url', models.URLField(blank=True)),
                ('website_url', models.URLField(blank=True)),
                ('booth_number', models.CharField(blank=True, max_length=20)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhibitors', to='events.event')),
                ('staff', models.ManyToManyField(blank=True, related_name='exhibitor_roles', to='attendees.registration')),
            ],
            options={
                'ordering': ['tier', 'name'],
                'unique_together': {('event', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('captured_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captured_leads', to='attendees.registration')),
                ('exhibitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='exhibitors.exhibitor')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='attendees.registration')),
            ],
            options={
                'ordering': ['-captured_at'],
                'unique_together': {('exhibitor', 'registration')},
            },
        ),
    ]
